from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'Calculadora_Icon.png'

# Colors
PRIMARY_COLOR = "#140599"
DARKER_PRIMARY_COLOR = "#035a83"
DARKEST_PRIMARY_COLOR = "#032A3B"

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500